version: "3.8"
services:
  chatto.web:
    image: chatto-web
    container_name: chatto.web
    build:
      context: . 
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000