version: "3.8"
services:
  chatto.web:
    image: chatto-web
    container_name: chatto.web
    build:
      context: . 
      dockerfile: Dockerfile
    command: pnpm dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000