version: '3.4'

networks:
  dev:
    driver: bridge

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    depends_on:
        - "chatto.database"
    container_name: chatto.api
    ports:
        - "8080:80" 
    build:
        context: .
        dockerfile: API/Dockerfile
    environment:
        - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=chatto.database;Port=5432;Database=chatto;
        - ASPNETCORE_URLS=http://+:80
        - JwtSettings__Key=c5bb980c73014f67ad5b6b3e052bafdb
        - JwtSettings__Issuer=https://localhost:8080/
        - JwtSettings__Audience=https://localhost:8080/
        - JwtSettings__TokenValidityFromDays=3
        - BackBlaze__Secrets__KeyId=005cf87f2ead8ec0000000002
        - BackBlaze__Secrets__ApplicationKey=K005vu4PI//XBsVoxGO3xRFsWaOwnt4
        - BackBlaze__Bucket__Name=chatto-cloud-repository
        - BackBlaze__Bucket__Id=ac3fb827bf72ce1a8de80e1c
        - BackBlaze__Bucket__Endpoint=s3.us-east-005.backblazeb2.com  
        - GoogleAuthSettings__ClientId=
        - GoogleAuthSettings__ClientSecret=
        - MailjetSettings__ApiKey=1f9de662735a6ae3d84a7941551e0e16
        - MailjetSettings__ApiSecret=1caf1ff40f05d230cf27f8e685a8c822
    networks:
        - dev

  chatto.database:
    image: postgres:latest
    container_name: chatto.database
    environment:
        POSTGRES_DB : chatto
        POSTGRES_USER : postgres
        POSTGRES_PASSWORD : postgres
    ports:
        - 5433:5432
    volumes:
        - "chatto-db:/var/lib/postgresql/data"
    networks:
            - dev

volumes:
    chatto-db:
    
  

