version: '3.4'

networks:
  dev:
    driver: bridge

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    depends_on:
        - "chatto.database"
    container_name: chatto.api
    ports:
        - "8080:80" 
    build:
        context: .
        dockerfile: API/Dockerfile
    networks:
        - dev

  chatto.database:
    image: postgres:latest
    container_name: chatto.database
    environment:
        POSTGRES_DB : chatto
        POSTGRES_USER : postgres
        POSTGRES_PASSWORD : postgres
    ports:
        - 5433:5432
    volumes:
        - "chatto-db:/var/lib/postgresql/data"
    networks:
            - dev

volumes:
    chatto-db:
    
  

