name: Mobile

on:
  push:
    paths:
      - 'mobile/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        working-directory: mobile

      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew test
        working-directory: mobile

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build
        working-directory: mobile

      # Create APK Debug
      - name: Build apk debug project (APK)
        run: ./gradlew assembleDebug
        working-directory: mobile

      # Create APK Release
      - name: Build apk release project (APK)
        run: ./gradlew assemble
        working-directory: mobile
        if: github.ref == 'refs/heads/main'

      # Create Bundle AAB Release
      - name: Build app bundle release (AAB)
        run: ./gradlew bundleRelease
        working-directory: mobile
        if: github.ref == 'refs/heads/main'

      # Upload Artifact Build
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) debug generated
          path: mobile/build/outputs/apk/debug/

      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) release generated
          path: mobile/build/outputs/apk/release/
        if: github.ref == 'refs/heads/main'

      - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
          path: mobile/build/outputs/bundle/release/
        if: github.ref == 'refs/heads/main'